version: '3'

services:
  nginx:
    image: nginx:1.15.10-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - web
  web:
    image: asset-tracker-static
    build:
      context: ./client/
  app:
    image: asset-tracker
    build:
      context: ./server/
    depends_on:
      - mongo
  mongo:
    image: mongo:4.0.8
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local